config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present? && Account.where(subdomain: request.subdomain).first
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    root 'lessons#index', as: :subdomain_root
    devise_for :users
  end

  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
  end
  root 'welcome#index', as: :welcome_root
end

app/models/account.rb
class Account < ApplicationRecord
  RESTRICTED_SUBDOMAIN = %w[www]

  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
                        uniqueness: { case_sensitive: false },
                        format: { with: /\A[\w\-]+\Z/i, message: 'Zawiera nieprawidłowe znaki' },
                        exclusion: { in: RESTRICTED_SUBDOMAIN, message: 'Zabroniony' }
  before_validation :downcase_subdomain

  accepts_nested_attributes_for :owner
  private
  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.valid?
      Apartment::Tenant.create(@account.subdomain)
      Apartment::Tenant.switch!(@account.subdomain)
      @account.save
      redirect_to new_user_session_url(subdomain: @account.subdomain)
      # redirect_to root_path, notice: 'Rejestracja została zakończona pomyślnie'
    else
      render :new
    end
  end

  private

  def account_params
    params.require(:account).permit(:subdomain, owner_attributes: [:first_name, :last_name, :email, :password, :password_confirmation])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  before_action :load_schema, :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_in){|u| u.permit(:email, :password, :password_confirmation, :remember_me)}
      devise_parameter_sanitizer.permit(:sign_up){|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :remember_me)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar, :first_name, :last_name, :email, :password, :password_confirmation, :current_password) }
    end

    def load_schema
      # Apartment::Tenant.switch!('public')
      Apartment::Tenant.reset
      return unless request.subdomain.present?

      account = Account.where(subdomain: request.subdomain).first
      if account
        Apartment::Tenant.switch!(request.subdomain)
      else
        redirect_to root_url(request.domain)
      end
    end

    def after_sign_out_path_for(resource_or_scope)
      new_user_session_path
    end

    # def validate_subdomain
    #   redirect_to welcome_root_path unless Account.where(subdomain: request.subdomain).first
    # end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    # return if flash[0][0] == :form_error
    flash.each do |msg_type, message|
      next if msg_type == :form_error
      concat(content_tag(:div, message.html_safe, {
        class: "alert #{bootstrap_class_for(msg_type)} fade in", style: "opacity:1;"}) do
          concat content_tag(:button, 'x', class: "close", data: {
          dismiss: 'alert'
        })
        concat message.html_safe
      end)
    end
    nil
  end
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:small, form.object.errors[field].try(:first), class: "help-block")
  end

  def form_group_for(form, field, text=field, &block)
    has_errors = form.object.errors[field].present?


    content_tag :div, class: "form-group #{'is-invalid' if has_errors}" do
      concat form.label(text, class: 'control-label', for: field)
      concat capture(&block)
      concat errors_for(form, field)
    end
  end


end
# .custom-file
# %input#customFile.custom-file-input{:type => "file"}/
# %label.custom-file-label{:for => "customFile"} Choose file

app/helpers/layout_helper.rb
module LayoutHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }
    .join
      sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)
      html = <<-HTML
      <div class="alert alert-error alert-block alert-fixed">
    <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/views/accounts/new.html.haml
.col-md-8.m-auto
  .card
    .card-header
      %h2 Utwórz konto
    .card-body
      = form_for @account do |f|
        = f.fields_for :owner do |o|
          = form_group_for o, :first_name, "Imie" do
            = o.text_field :first_name, class: "form-control"
          = form_group_for o, :last_name, "Nazwisko" do
            = o.text_field :last_name, class: "form-control"
          = form_group_for o, :email do
            = o.email_field :email, class: "form-control"
          = form_group_for o, :password, "Hasło" do
            = o.password_field :password, class: "form-control"
          = form_group_for o, :password_confirmation, "Potwierdzenie hasła" do
            = o.password_field :password_confirmation, class: "form-control"
        .form-group
          = form_group_for f, :subdomain do
            = f.text_field :subdomain, class: "form-control"
            .input-group-append
              %span.input-group-text .timetracker.dev
        = f.submit "Utwórz konto", class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Timetracker
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body
    %header.container.mb-3
      %nav.navbar.navbar-light.bg-light
        = link_to "Time Tracker", root_path, class: "navbar-brand"
        .pull-right.right-buttons
          - if user_signed_in?
            = link_to "Wyloguj się", destroy_user_session_path, method: 'delete', class: "btn btn-light navbar-btn"
    .container
      
      = flash_messages layout_flash: false
      .row
        = yield

app/views/lessons/index.html.haml
%h1 Witaj

app/views/welcome/index.html.haml
.col-md-12
  .jumbotron
    %h1 Organizer
    %p Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis ab quasi esse minima vel fuga quaerat placeat ipsum neque? Debitis?
    %p= link_to "Utwórz konto", new_account_path, class: "btn btn-primary btn-lg"